(MODULES-4352) Restrict parameter :replace to values accepted by file
The replace parameter accepts an arbitrary string as opposed to the
file type's replace parameter.

This restricts the values to the same set that the file resource accepts
and replaces:

Error: /Stage[main]/Main/Concat_file[/tmp/foo]: Failed to generate
additional resources using 'generate': Parameter replace failed on
File[/tmp/foo]: Invalid value "foo". Valid values are true, false,
yes, no.
Error: /Stage[main]/Main/Concat_file[/tmp/foo]: Failed to generate
additional resources using 'eval_generate': undefined method `ref' for
nil:NilClass

with a more easily understandable:

Error: Parameter replace failed on Concat_file[/tmp/foo]: Invalid value
"foo". Valid values are true, false, yes, no.  at /tmp/foo.pp:1

It also lets :ensure_newline inherit Puppet::Parameter::Boolean to make
it consistent with the other parameters.