(MODULES-4350) Fix path parameter not being a namevar.
With path not a key attribute it's possible for multiple concat_file
resources to manage the same path.

For example, this compiles fine and creates a file:

-------foo.pp----------
concat_file { 'foo':
  ensure => present,
  path   =>  '/tmp/foo',
}

concat_file { 'bar':
  ensure => present,
  path   =>  '/tmp/foo',
}
-----------------------
tdevelioglu@traveler:/tmp$ puppet apply foo.pp
Notice: Compiled catalog for traveler.ams4.prod.booking.com in
environment production in 0.07 seconds
Notice: /Stage[main]/Main/File[/tmp/foo]/ensure: created
Notice: Applied catalog in 0.02 seconds

This makes :path the namevar for concat_file so we get:

tdevelioglu@traveler:/tmp$ puppet apply foo.pp
Error: Evaluation Error: Error while evaluating a Resource Statement,
Cannot alias Concat_file[bar] to ["/tmp/foo"] at /tmp/foo.pp:6; resource
["Concat_file", "/tmp/foo"] already declared at /tmp/foo.pp:1 at
/tmp/foo.pp:6:1 on node traveler.ams4.prod.booking.com